
all: bn_sample

bn_sample: bn_sample.c
	gcc bn_sample.c -o bn_sample -lcrypto

task_1: task_1.c
	gcc task_1.c -o task_1 -lcrypto

task_2: task_2.c
	gcc task_2.c -o task_2 -lcrypto

task_3: task_3.c
	gcc task_3.c -o task_3 -lcrypto

task_4: task_4.c
	gcc task_4.c -o task_4 -lcrypto

task_5: task_5.c
	gcc task_5.c -o task_5 -lcrypto

task_6: task_6.c
	gcc task_6.c -o task_6 -lcrypto

clean:
	rm -f bn_sample task_1 task_2 task_3 task_4 task_5 task_6 *.o
